// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

package org.usfirst.frc6408.SingleJoystickControls.subsystems;

import org.usfirst.frc6408.SingleJoystickControls.RobotMap;
import org.usfirst.frc6408.SingleJoystickControls.commands.*;

import edu.wpi.first.wpilibj.RobotDrive;
import edu.wpi.first.wpilibj.command.Subsystem;


public class DriveTrain extends Subsystem {
	private RobotDrive drive = new RobotDrive(0, 1, 2, 3);

    public void initDefaultCommand() {
    }
   
}

