// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

package org.usfirst.frc6408.SingleJoystickControls.subsystems;

import org.usfirst.frc6408.SingleJoystickControls.RobotMap;
import org.usfirst.frc6408.SingleJoystickControls.commands.*;

import edu.wpi.first.wpilibj.RobotDrive;
import edu.wpi.first.wpilibj.command.Subsystem;


public class DriveTrain extends Subsystem {
	private RobotDrive drive = new RobotDrive(0, 1, 14, 15);

    public void initDefaultCommand() 
    {
        // Set the default command for a subsystem here.
    }
    
    public void driveDirection (double ySpeed, double turnSpeed, double xSpeed, double throttle)
    {
    	// Uses x, y, and z axis of the joystick to turn the robot.
    	// Z turns the robot in that direction, x turns the robot's wheels on both sides, y moves the robot forwards or backwards. 
    	if(turnSpeed < 0) {
    		drive.setLeftRightMotorOutputs((ySpeed - (xSpeed / 2)) * throttle, (ySpeed - turnSpeed + (xSpeed / 2))* throttle); 
    	}
    	else {
    		drive.setLeftRightMotorOutputs((ySpeed + turnSpeed - (xSpeed / 2)) * throttle, (ySpeed + (xSpeed / 2)) * throttle);
    	}
    	
    }
}

